name = "wizard-intro"
love_files = ["::git-ls-tree::"] # all files tracked by git
default_targets = ["appimage"]
build_directory = "builds"

[appimage]
# NOTE: it may be platform-dependent
# see for details: https://github.com/thewizardplusplus/wizard-intro/issues/20
shared_libraries = [
  "/lib/x86_64-linux-gnu/libz.so.1",
  "/lib/x86_64-linux-gnu/libfreetype.so.6",
  "/lib/x86_64-linux-gnu/libmpg123.so.0",
]
